# utils/hw_calibration.py
# Калибровка "HW" (аналоговый датчик влажности почвы) + сохранение в config_*.py
# Зависимости: machine, time. Работает с SoilMoistureHWSensor (нужны read_raw(), wet_value, dry_value).

import machine
import time


def _collect_stable_value(read_raw_fn, seconds: float = 3.0, interval_ms: int = 50):
    """
    Собирает значения read_raw_fn() в течение N секунд и возвращает (avg, min, max).
    """
    t_end = time.ticks_add(time.ticks_ms(), int(seconds * 1000))
    vals = []
    while time.ticks_diff(t_end, time.ticks_ms()) > 0:
        v = read_raw_fn()
        if v is not None:
            vals.append(v)
        time.sleep_ms(interval_ms)

    if not vals:
        return None, None, None

    avg = sum(vals) // len(vals)
    return avg, min(vals), max(vals)


def _wait_press_release(btn: machine.Pin, active_low: bool = True):
    def is_pressed():
        v = btn.value()
        return (v == 0) if active_low else (v == 1)

    # ждём нажатие
    while not is_pressed():
        time.sleep_ms(20)

    # антидребезг + ждём отпускание
    time.sleep_ms(80)
    while is_pressed():
        time.sleep_ms(20)
    time.sleep_ms(120)



# utils/hw_calibration_store.py
# Безопасное обновление config_hw.py (атомарная запись через временный файл + replace/rename).
#
# Идея:
#  1) пишем новый файл во временный путь
#  2) (опционально) сохраняем бэкап старого
#  3) атомарно подменяем config_hw.py
#
# Это существенно снижает шанс получить "битый" config_hw.py при внезапном выключении питания.

import os
import time


def _safe_replace(src_path: str, dst_path: str) -> bool:
    """
    Пытается заменить dst_path на src_path как можно более атомарно.
    В MicroPython поведение зависит от FS, поэтому делаем best-effort:
      - если есть os.replace — используем
      - иначе: удалить dst и переименовать
    """
    try:
        # CPython и часть сборок MicroPython
        replace = getattr(os, "replace", None)
        if replace:
            replace(src_path, dst_path)
            return True

        # fallback
        try:
            os.remove(dst_path)
        except OSError:
            pass
        os.rename(src_path, dst_path)
        return True
    except Exception as e:
        print("safe_replace error:", e)
        return False


def update_config_hw_py_safe(
    wet_value: int,
    dry_value: int,
    path: str = "config_hw.py",
    backup: bool = True,
    validate: bool = True,
) -> bool:
    """
    Безопасно обновляет/создаёт config_hw.py.

    wet_value, dry_value — сырые ADC значения калибровки.

    validate=True:
      - приводим к int
      - если wet > dry — меняем местами (типично dry>wet)
      - примитивные проверки на None
    """
    if wet_value is None or dry_value is None:
        return False

    try:
        wet = int(wet_value)
        dry = int(dry_value)
    except Exception:
        return False

    if validate and wet > dry:
        # чтобы стандартная формула 0..100 работала ожидаемо
        wet, dry = dry, wet

    # контент минимальный (экономно по памяти/flash)
    content = (
        "# Autogenerated by HW calibration. You may edit this file manually.\n"
        f"HW_WET_VALUE = {wet}\n"
        f"HW_DRY_VALUE = {dry}\n"
    )

    tmp_path = path + ".tmp"

    # 1) пишем tmp
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            f.write(content)
            # flush/sync в MicroPython не всегда доступны; close() важнее всего
    except Exception as e:
        print("write tmp error:", e)
        # best-effort cleanup
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        return False

    # 2) backup (best-effort)
    if backup:
        try:
            # если старый файл есть — бэкапнем
            with open(path, "r", encoding="utf-8") as f:
                old = f.read()
            with open(path + ".bak", "w", encoding="utf-8") as f:
                f.write(old)
        except Exception:
            # если файла нет или бэкап не записался — не критично
            pass

    # 3) подмена
    ok = _safe_replace(tmp_path, path)
    if not ok:
        # если не смогли заменить — tmp оставлять плохо
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        return False

    return True
