[mqtt]
mqtt-1 ansible_host=<MQTT_1_IP> ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ansible
mqtt-2 ansible_host=<MQTT_2_IP> ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ansible
