persistence true
persistence_location /mosquitto/data/
log_dest stdout

listener 1883 0.0.0.0

# пока включим анонимный доступ, чтобы не мучиться с passwords
allow_anonymous true

# Dynamic security plugin
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/config/dynamic-security.json
