version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    user: "0:0" 
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: no

  retain-cleaner:
    build: ./services/retain-cleaner
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: retain-cleaner
      MQTT_USERNAME: ${MQTT_USERNAME:-}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-}
    depends_on:
      - mosquitto
    restart: no
  
  fake-data:
    build: ./services/fake-data
    depends_on:
      - mosquitto
    restart: no

  db:
    image: timescale/timescaledb-ha:pg16.11-ts2.23.0-all-oss
    container_name: pvz_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pvz}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-pvzdb}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
